parameters:
    app:
        pagination:
            default_page_size: 10
            max_page_size: 50
            default_page: 1
        
        news:
            title:
                min_length: 3
                max_length: 255
            short_desc:
                min_length: 10
                max_length: 500
            content:
                min_length: 50
            recent_limit: 3
            top_limit: 10
        
        category:
            title:
                min_length: 2
                max_length: 255
        
        comment:
            author:
                min_length: 2
                max_length: 255
            content:
                min_length: 10
                max_length: 1000
        
        file_upload:
            max_size: 5242880  # 5MB
            allowed_types:
                - 'image/jpeg'
                - 'image/png'
                - 'image/gif'
            directory: 'uploads/pictures'
        
        email:
            max_length: 255
            weekly_stats:
                subject: 'Weekly News Statistics - Top 10 Articles'
                from: 'noreply@newsportal.com'
        
        security:
            csrf_token:
                comment: 'comment_item'
                news: 'news_item'
                category: 'category_item'
        
        validation:
            name_pattern: '/^[a-zA-Z0-9\s\-]+$/'
            no_html_pattern: '/^[^<>]*$/'
        
        messages:
            news:
                title_required: 'Please enter a title'
                title_length: 'Title must be between {{ limit }} and {{ limit }} characters'
                short_desc_required: 'Please enter a short description'
                short_desc_length: 'Short description must be between {{ limit }} and {{ limit }} characters'
                content_required: 'Please enter the content'
                content_min_length: 'Content must be at least {{ limit }} characters long'
                image_type: 'Please upload a valid image file (JPEG, PNG, GIF)'
                image_size: 'Image size must be less than 5MB'
                category_required: 'Please select at least one category'
            category:
                title_required: 'Please enter a category title'
                title_length: 'Category title must be between {{ limit }} and {{ limit }} characters'
            comment:
                author_required: 'Please enter your name'
                author_length: 'Name must be between {{ limit }} and {{ limit }} characters'
                author_pattern: 'Name can only contain letters, numbers, spaces and hyphens'
                email_invalid: 'Please enter a valid email address'
                email_length: 'Email cannot be longer than {{ limit }} characters'
                content_required: 'Please enter your comment'
                content_length: 'Comment must be between {{ limit }} and {{ limit }} characters'
                content_pattern: 'HTML tags are not allowed in comments' 