# Public routes
app_public_index:
    path: /
    controller: App\Controller\Public\PublicController::index
    methods: [GET]

app_public_category:
    path: /category/{id}
    controller: App\Controller\Public\PublicController::category
    methods: [GET]
    requirements:
        id: '\d+'

app_public_news:
    path: /news/{id}
    controller: App\Controller\Public\PublicController::news
    methods: [GET]
    requirements:
        id: '\d+'

app_public_comment:
    path: /news/{id}/comment
    controller: App\Controller\Public\PublicController::comment
    methods: [POST]
    requirements:
        id: '\d+'

# Admin routes
app_admin_index:
    path: /admin
    controller: App\Controller\Admin\AdminController::index
    methods: [GET]

app_admin_login:
    path: /admin/login
    controller: App\Controller\Admin\AdminController::login
    methods: [GET, POST]

app_admin_logout:
    path: /admin/logout
    controller: App\Controller\Admin\AdminController::logout
    methods: [POST]

# Admin Category routes
app_admin_category_index:
    path: /admin/category
    controller: App\Controller\Admin\AdminCategoryController::index
    methods: [GET]

app_admin_category_new:
    path: /admin/category/new
    controller: App\Controller\Admin\AdminCategoryController::new
    methods: [GET, POST]

app_admin_category_show:
    path: /admin/category/{id}
    controller: App\Controller\Admin\AdminCategoryController::show
    methods: [GET]
    requirements:
        id: '\d+'

app_admin_category_edit:
    path: /admin/category/{id}/edit
    controller: App\Controller\Admin\AdminCategoryController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'

app_admin_category_delete:
    path: /admin/category/{id}
    controller: App\Controller\Admin\AdminCategoryController::delete
    methods: [POST]
    requirements:
        id: '\d+'

# Admin News routes
app_admin_news_index:
    path: /admin/news
    controller: App\Controller\Admin\AdminNewsController::index
    methods: [GET]

app_admin_news_new:
    path: /admin/news/new
    controller: App\Controller\Admin\AdminNewsController::new
    methods: [GET, POST]

app_admin_news_show:
    path: /admin/news/{id}
    controller: App\Controller\Admin\AdminNewsController::show
    methods: [GET]
    requirements:
        id: '\d+'

app_admin_news_edit:
    path: /admin/news/{id}/edit
    controller: App\Controller\Admin\AdminNewsController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'

app_admin_news_delete:
    path: /admin/news/{id}
    controller: App\Controller\Admin\AdminNewsController::delete
    methods: [POST]
    requirements:
        id: '\d+'

# Admin Comment routes
app_admin_comment_index:
    path: /admin/comment
    controller: App\Controller\Admin\AdminCommentController::index
    methods: [GET]

app_admin_comment_show:
    path: /admin/comment/{id}
    controller: App\Controller\Admin\AdminCommentController::show
    methods: [GET]
    requirements:
        id: '\d+'

app_admin_comment_delete:
    path: /admin/comment/{id}
    controller: App\Controller\Admin\AdminCommentController::delete
    methods: [POST]
    requirements:
        id: '\d+'

app_admin_news_comments:
    path: /admin/news/{id}/comments
    controller: App\Controller\Admin\AdminCommentController::newsByComments
    methods: [GET]
    requirements:
        id: '\d+' 