parameters:
    # Directory for uploaded pictures
    pictures_directory: '%kernel.project_dir%/public/uploads/pictures'
    # Email configuration for weekly stats
    stats_email: '%env(STATS_EMAIL)%'
    from_email: '%env(FROM_EMAIL)%'
    # Pagination configuration
    pagination.items_per_page: 10

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\WeeklyStatsEmailService:
        arguments:
            $statsEmail: '%stats_email%'
            $fromEmail: '%from_email%'


